"""Added tags to Post user model

Revision ID: 9092ef4aa74a
Revises: 7e681f8c283a
Create Date: 2023-04-01 23:53:34.754790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9092ef4aa74a'
down_revision = '7e681f8c283a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    # ### end Alembic commands ###
