"""Removed tags from Post user model

Revision ID: d4ad2f800764
Revises: 9092ef4aa74a
Create Date: 2023-04-02 01:43:38.711216

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd4ad2f800764'
down_revision = '9092ef4aa74a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
